# Generated by Django 5.0.1 on 2024-01-06 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ServerApi.tag'),
        ),
    ]
