# Generated by Django 5.0.1 on 2024-01-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApi', '0002_alter_product_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_tags',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
